Test Ci 18

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -59,16 +59,15 @@ jobs:
           command: docker build -t scrabble .
       - run:
           name: Start Docker Compose
-          command: |
-            docker compose -f 'docker-compose-test.yml' up
-            test_result=$?
-      
-            if [ $test_result -eq 0 ]; then
-              echo "Tests passed successfully. Continuing with the workflow."
-            else
-              echo "Tests failed. Stopping the workflow."
-              exit 1
-            fi
+          command: docker compose -f 'docker-compose-test.yml' up
+#            test_result=$?
+#
+#            if [ $test_result -eq 0 ]; then
+#              echo "Tests passed successfully. Continuing with the workflow."
+#            else
+#              echo "Tests failed. Stopping the workflow."
+#              exit 1
+#            fi
 
             
 
